#!/usr/bin/env sh

TMP_DIR="/tmp/rmpc"

mkdir -p "$TMP_DIR"

ALBUM_ART_PATH="$TMP_DIR/notification_cover"

if ! rmpc albumart --output "$ALBUM_ART_PATH"; then
    ALBUM_ART_PATH=""
fi

notify-send -a "Music Player Daemon" -i "${ALBUM_ART_PATH}" "$ARTIST - $TITLE" "$ALBUM, track $TRACK"
